### ISSUE TITLE
How to use the package

### ISSUE THREAD

**Issue by fkromer** [duboviy/extdbg#1]
Hi @duboviy, could you provide some video tutorial or docs about how the package can be used?

**Comment by duboviy** [comment]
@fkromer  you're right, fully agree with you about package documentation, I'll add it ASAP...

**Comment by fkromer** [comment]
If providing video tutorials would save you time I would contribute by extracting these information into the docs. Just give me some hint where I can add content to the [extdbg docs](https://pythonhosted.org/extdbg/) (the sources seem to be private).

**Comment by duboviy** [comment]
oh yeap, sure,
I've generated [extdbg docs](https://pythonhosted.org/extdbg/) using [mkdocs utility](http://www.mkdocs.org/).
So I've just passed [README.md](https://github.com/duboviy/extdbg/blob/master/README.md) to utility - this way documentation was built and then uploaded.

Sorry for such confusing and complicated scheme...
So if you would like to contribute - feel free to add changes to [README.md](https://github.com/duboviy/extdbg/blob/master/README.md) or maybe some new /docs/... folder and I'll merge them.
